name = "meta_test"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MetaTest"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "MetaTest"
